FROM python:3.12-slim

RUN pip install poetry

COPY poetry.lock ./
COPY pyproject.toml ./

RUN poetry install --no-interaction --no-ansi

COPY scripts/huey /
COPY src/*.py /
ENTRYPOINT [ "poetry", "run", "./huey" ]
