services:
  main:
    build: .
    platform: linux/amd64
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      DB_CONNECT_STRING: $DB_CONNECT_STRING
      DB_USER: $DB_USER
      DB_HOST: $DB_HOST
      DB_PASSWORD: $DB_PASSWORD
      TWILIO_AUTH_TOKEN: $TWILIO_AUTH_TOKEN
      LOGLEVEL: $LOGLEVEL
    volumes:
      - ./src/static:/src/static
    image: git.tcrez.dev/tcrez/checkin-viz

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    platform: linux/amd64
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DB_CONNECT_STRING: $DB_CONNECT_STRING
      DB_USER: $DB_USER
      DB_HOST: $DB_HOST
      DB_PASSWORD: $DB_PASSWORD
      TWILIO_AUTH_TOKEN: $TWILIO_AUTH_TOKEN
      LOGLEVEL: $LOGLEVEL
      DISCORD_TOKEN: $DISCORD_TOKEN
      ALLOWED_MESSAGE_CHANNEL_ID: $ALLOWED_MESSAGE_CHANNEL_ID

  rq-cron:
    build:
      context: .
      dockerfile: Dockerfile.rq
    platform: linux/amd64
    restart: unless-stopped
    entrypoint: poetry run rq cron tasks.py --url redis://valkey:6379
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      TZ: America/New_York
      DB_CONNECT_STRING: $DB_CONNECT_STRING
      DB_USER: $DB_USER
      DB_HOST: $DB_HOST
      DB_PASSWORD: $DB_PASSWORD
      TWILIO_AUTH_TOKEN: $TWILIO_AUTH_TOKEN
      LOGLEVEL: $LOGLEVEL
      DISCORD_TOKEN: $DISCORD_TOKEN
      ALLOWED_MESSAGE_CHANNEL_ID: $ALLOWED_MESSAGE_CHANNEL_ID
    depends_on:
      valkey:
        condition: service_healthy

  rq-worker:
    build:
      context: .
      dockerfile: Dockerfile.rq
    platform: linux/amd64
    restart: unless-stopped
    entrypoint: poetry run rq worker cron -u redis://valkey:6379
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      TZ: America/New_York
      DB_CONNECT_STRING: $DB_CONNECT_STRING
      DB_USER: $DB_USER
      DB_HOST: $DB_HOST
      DB_PASSWORD: $DB_PASSWORD
      TWILIO_AUTH_TOKEN: $TWILIO_AUTH_TOKEN
      LOGLEVEL: $LOGLEVEL
      DISCORD_TOKEN: $DISCORD_TOKEN
      ALLOWED_MESSAGE_CHANNEL_ID: $ALLOWED_MESSAGE_CHANNEL_ID
    depends_on:
      valkey:
        condition: service_healthy

  valkey:
    hostname: valkey
    image: valkey/valkey:9-alpine
    restart: unless-stopped
    environment:
      TZ: America/New_York
    healthcheck:
      test: ["CMD-SHELL", "valkey-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
